name: Matrix Map Test

on: [push]

env:
  BUILD_CONFIGURATION: Release
  FOLDER_NAME: workspace

jobs:

  compile_tools:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Write Config File
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        "`$Config = @{ 'projectName' = 'Cold Ice Remastered' }" | Add-Content .\${{env.FOLDER_NAME}}\Config.ps1

    - name: Compile tools
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        .\${{env.FOLDER_NAME}}\Build-Tools.ps1 -ConfigFile Config
        [void](New-Item -Force -ItemType Directory $env:TEMP\bin)
        Copy-Item -Recurse -Force .\bin $env:TEMP
        Compress-Archive -LiteralPath $env:TEMP\bin -DestinationPath .\tools.zip -Force

    - name: Upload tools
      uses: actions/upload-artifact@v2
      with:
        name: compiled_tools
        path: ./${{env.FOLDER_NAME}}/tools.zip

  compile_maps:
    runs-on: windows-latest
    needs: [compile_tools]
    strategy:
      matrix:
        map: [snowyard,fences]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Download tools
      uses: actions/download-artifact@v2
      with:
        name: compiled_tools
        path: ./${{env.FOLDER_NAME}}

    - name: Unpack tools
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        Expand-Archive -Path .\${{env.FOLDER_NAME}}\tools.zip -DestinationPath $env:TEMP
        Remove-Item .\${{env.FOLDER_NAME}}\bin\\* -Recurse -Force -ErrorAction Ignore
        Remove-Item .\${{env.FOLDER_NAME}}\bin -Force -ErrorAction Ignore
        Move-Item $env:TEMP\bin .\${{env.FOLDER_NAME}}
        Remove-Item .\${{env.FOLDER_NAME}}\tools.zip -Recurse -Force -ErrorAction Ignore

    - name: Write Config File
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        "`$Config = @{ 'projectName' = 'Cold Ice Remastered' }" | Add-Content .\${{env.FOLDER_NAME}}\Config.ps1

    - name: Compile ${{matrix.map}}
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        .\${{env.FOLDER_NAME}}\Build-Maps.ps1 -Clean -ConfigFile Config -Map ${{matrix.map}}
        [void](New-Item -Force -ItemType Directory $env:TEMP\maps)
        Copy-Item -Recurse -Force .\redist\maps $env:TEMP
        Get-ChildItem -Path .\redist\ -Filter *.wad | Copy-Item -Destination $env:TEMP -Force -PassThru
        Compress-Archive -LiteralPath $env:TEMP\maps -DestinationPath .\${{matrix.map}}.zip -Force
        Get-ChildItem -Path $env:TEMP -Filter *.wad | Compress-Archive -DestinationPath .\${{matrix.map}}.zip -Update

    - name: Upload ${{matrix.map}}
      uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.map}}
        path: ./${{env.FOLDER_NAME}}/${{matrix.map}}.zip

  combine_maps:
    runs-on: windows-latest
    needs: [compile_maps]

    steps:
    - uses: actions/download-artifact@v2
      with:
        path: ./${{env.FOLDER_NAME}}

    - name: Combine Maps
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        [void](New-Item -Force -ItemType Directory $env:TEMP\maps)
        Expand-Archive -Path .\${{env.FOLDER_NAME}}\snowyard.zip -DestinationPath $env:TEMP
        Move-Item $env:TEMP\snowyard $env:TEMP\maps
        Expand-Archive -Path .\${{env.FOLDER_NAME}}\fences.zip -DestinationPath $env:TEMP
        Move-Item $env:TEMP\fences $env:TEMP\maps
        Copy-Item -Recurse -Force .\redist\maps $env:TEMP
        Get-ChildItem -Path .\redist\ -Filter *.wad | Copy-Item -Destination $env:TEMP -Force -PassThru
        Compress-Archive -LiteralPath $env:TEMP\maps -DestinationPath .\maps.zip -Force
        Get-ChildItem -Path $env:TEMP -Filter *.wad | Compress-Archive -DestinationPath .\maps.zip -Update

    - name: Upload Maps
      uses: actions/upload-artifact@v2
      with:
        name: compiled_maps
        path: ./${{env.FOLDER_NAME}}/maps.zip

  package_coldice:
    runs-on: windows-latest
    needs: [combine_maps]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Download maps
      uses: actions/download-artifact@v2
      with:
        name: compiled_maps
        path: ./${{env.FOLDER_NAME}}

    - name: Unpack maps
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        Expand-Archive -Path .\${{env.FOLDER_NAME}}\maps.zip -DestinationPath $env:TEMP
        Move-Item $env:TEMP\maps .\${{env.FOLDER_NAME}}\redist
        Get-ChildItem -Path $env:TEMP -Filter *.wad | Move-Item -Destination .\${{env.FOLDER_NAME}}\redist -Force -PassThru
        Remove-Item .\${{env.FOLDER_NAME}}\maps.zip -Recurse -Force -ErrorAction Ignore

    - name: Download tools
      uses: actions/download-artifact@v2
      with:
        name: compiled_tools
        path: ./${{env.FOLDER_NAME}}

    - name: Unpack tools
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        Expand-Archive -Path .\${{env.FOLDER_NAME}}\tools.zip -DestinationPath $env:TEMP
        Remove-Item .\${{env.FOLDER_NAME}}\bin\\* -Recurse -Force -ErrorAction Ignore
        Remove-Item .\${{env.FOLDER_NAME}}\bin -Force -ErrorAction Ignore
        Move-Item $env:TEMP\bin .\${{env.FOLDER_NAME}}
        Remove-Item .\${{env.FOLDER_NAME}}\tools.zip -Recurse -Force -ErrorAction Ignore

    - name: Write Config File
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        "`$Config = @{ 'projectName' = 'Cold Ice Remastered'`r`n'gameFolder' = 'ice_beta1' }" | Add-Content .\${{env.FOLDER_NAME}}\Config.ps1

    - name: Package and verify Cold Ice
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: .\${{env.FOLDER_NAME}}\Build-Release.ps1 -ConfigFile Config

    - name: Archive Cold Ice Release
      uses: actions/upload-artifact@v2
      with:
        name: coldice-build
        path: .\${{env.FOLDER_NAME}}\cold-ice-remastered-git-*.zip
        if-no-files-found: error
